changes for pipeline-watchdog
urbanrobo/gstreamer-monorepo pull request #2
Opened 2024-01-18 22:38 UTC by Rishabh-halo

2024-01-18 23:40 UTC, nabeel-halo requested changes

2024-01-18 23:40 UTC, nabeel-halo commented on subprojects/gst-plugins-bad/gst/debugutils/gstwatchdog.c
you have to free the string allocated by g_strdup_printf
```suggestion
g_free(watchdogInfo);
```

2024-01-19 01:14 UTC, nabeel-halo approved these changes

2024-01-19 18:20 UTC, Mdillon95 approved these changes

2024-01-19 18:22 UTC, merged